name = "feedback-api"
compatibility_date = "2024-08-26"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "FEEDD1"
database_name = "feedback-system"
database_id = "c3b23d4d-ce0b-4625-af13-572575c6ee86"

# [ai]
# binding = "AI"